Fixed dts path again and disable other jobs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,7 +41,7 @@ jobs:
           pip3 install -U --user tuxmake
           tuxmake --directory linux --build-dir=cache/ --target-arch=aarch64 -k $KBUILD_DEFCONFIG  --kconfig-add $KBUILD_DEFCONFIG_PMOS $TUXMAKE_EXTRA_OPTS
           cd /home/runner/.cache/tuxmake/builds/1/
-          skales-dtbtool -p scripts/dtc/ -o dt.img arch/arm64/boot/dts
+          skales-dtbtool -p scripts/dtc/ -o dt.img linux/arch/arm64/boot/dts
           tar -cf linux-${BRANCH}.tar *
           cd -
           mv /home/runner/.cache/tuxmake/builds/1/linux-${BRANCH}.tar ./
@@ -54,48 +54,48 @@ jobs:
           title: "Build ${{ matrix.kernel }}"
           files: |
             *.tar
-  dtbs:
-    strategy:
-      fail-fast: false
-      matrix:
-        kernel: [v5.9-rc1-ferrari]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/checkout@v2
-        with:
-          repository: ${{ env.KERNEL_GITHUB_REPOSITORY }}
-          ref: ${{ matrix.kernel }}
-          path: linux
-      - name: Build
-        run: |
-          sudo apt-get -qq update > /dev/null
-          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev dwarves python3-pip socat > /dev/null
-          pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
-          cd linux
-          make defconfig
-          status=0
-          make -j3 dtbs || status=1
-          make -j3 dtbs_check || status=1
-          exit $status
+  #dtbs:
+    #strategy:
+      #fail-fast: false
+      #matrix:
+        #kernel: [v5.9-rc1-ferrari]
+    #runs-on: ubuntu-latest
+    #steps:
+      #- uses: actions/checkout@v2
+      #- uses: actions/checkout@v2
+        #with:
+          #repository: ${{ env.KERNEL_GITHUB_REPOSITORY }}
+          #ref: ${{ matrix.kernel }}
+          #path: linux
+      #- name: Build
+        #run: |
+          #sudo apt-get -qq update > /dev/null
+          #sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev dwarves python3-pip socat > /dev/null
+          #pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
+          #cd linux
+          #make defconfig
+          #status=0
+          #make -j3 dtbs || status=1
+          #make -j3 dtbs_check || status=1
+          #exit $status
 
-  dt_bindings_check:
-    strategy:
-      fail-fast: false
-      matrix:
-        kernel: [v5.9-rc1-ferrari]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/checkout@v2
-        with:
-          repository: ${{ env.KERNEL_GITHUB_REPOSITORY }}
-          ref: ${{ matrix.kernel }}
-          path: linux
-      - name: Build
-        run: |
-          sudo apt-get -qq update > /dev/null
-          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev dwarves python3-pip socat > /dev/null
-          pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
-          cd linux
-          make -j3 dt_binding_check
+  #dt_bindings_check:
+    #strategy:
+      #fail-fast: false
+      #matrix:
+        #kernel: [v5.9-rc1-ferrari]
+    #runs-on: ubuntu-latest
+    #steps:
+      #- uses: actions/checkout@v2
+      #- uses: actions/checkout@v2
+        #with:
+          #repository: ${{ env.KERNEL_GITHUB_REPOSITORY }}
+          #ref: ${{ matrix.kernel }}
+          #path: linux
+      #- name: Build
+        #run: |
+          #sudo apt-get -qq update > /dev/null
+          #sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev ccache bison flex libelf-dev dwarves python3-pip socat > /dev/null
+          #pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
+          #cd linux
+          #make -j3 dt_binding_check
